site_name: FocusSuite Documentation
site_url: https://jassu2244.github.io/FocusSuite/
docs_dir: .docs
nav:
  - Home: index.md
  - Beginner's Guide: BEGINNER_GUIDE.md
  - Complete Documentation: DOCUMENTATION.md
  - Project Overview: PROJECT_OVERVIEW.md
  - Contributing Guide: CONTRIBUTING.md
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: indigo
markdown_extensions:
  - toc
  - tables
  - admonition
  - codehilite
